### ISSUE TITLE
Stopped working with Meteor 1.3.5.1

### ISSUE THREAD

**Issue by Richie765** [numtel/meteor-pg-server#3]
After an upgrade I discovered this module doesn't work with recent Meteor versions. Here's what I did:

``` bash
meteor create test
cd test
meteor add numtel:pg-server
```

Output

```
 => Errors while adding packages:

While loading package numtel:pg-server@1.0.1:
error: Command failed:
module.js:340
throw err;
^
Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(/private/var/richard/.meteor/packages/numtel_pg-server/.1.0.1.mtea66++os.osx.x86_64+web.browser+web.cordova/plugin.pgServer.os.osx.x86_64/npm/pgServer/node_modules/.temp-15gbep9/node_modules/pg-server-9.4-osx-x64/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)

npm ERR! Darwin 15.6.0
npm ERR! argv "node"
"/private/var/richard/.meteor/packages/meteor-tool/.1.3.5_1.1u6ft3z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v0.10.46
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/private/var/richard/.meteor/packages/numtel_pg-server/.1.0.1.mtea66++os.osx.x86_64+web.browser+web.cordova/plugin.pgServer.os.osx.x86_64/npm/pgServer/node_modules/.temp-15gbep9/npm-debug.log

module.js:340
throw err;
^
Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(/private/var/richard/.meteor/packages/numtel_pg-server/.1.0.1.mtea66++os.osx.x86_64+web.browser+web.cordova/plugin.pgServer.os.osx.x86_64/npm/pgServer/node_modules/.temp-15gbep9/node_modules/pg-server-9.4-osx-x64/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)

npm ERR! Darwin 15.6.0
npm ERR! argv "node"
"/private/var/richard/.meteor/packages/meteor-tool/.1.3.5_1.1u6ft3z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v0.10.46
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/private/var/richard/.meteor/packages/numtel_pg-server/.1.0.1.mtea66++os.osx.x86_64+web.browser+web.cordova/plugin.pgServer.os.osx.x86_64/npm/pgServer/node_modules/.temp-15gbep9/npm-debug.log
```
